

services:
    mysql:
        image: mysql:5.7
        container_name: atp_mysql
        environment:
            MYSQL_DATABASE: atp_mysql
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
        ports:
            - "3306:3306"
        volumes:
            - ./data/conf.d:/etc/mysql/conf.d
            - ./data/logs:/logs
            - ./data/mysql:/var/lib/mysql


    redis:
        image: redis
        container_name: redis
        command: redis-server /usr/local/etc/redis/redis.conf
        ports:
            - "6379:6379"
        volumes:
            - ./data:/data
            - ./redis.conf:/usr/local/etc/redis/redis.conf
